#!/usr/bin/env python3
"""
Unused QRY Files Detector

This script scans all files in the /include/qry/ folder and checks if they are
referenced anywhere in the codebase. Files that are not referenced are likely
orphaned and can be safely removed.

Author: GitHub Copilot
Date: 2025-08-13
"""

import os
import glob
import re
from pathlib import Path
from collections import defaultdict

def get_qry_files(qry_folder):
    """Get all .cfm files in the qry folder"""
    qry_files = []
    qry_path = Path(qry_folder)
    
    if not qry_path.exists():
        print(f"❌ QRY folder not found: {qry_folder}")
        return []
    
    for file in qry_path.glob("*.cfm"):
        qry_files.append(file.name)
    
    return sorted(qry_files)

def search_for_references(root_folder, filename):
    """Search for references to a filename in all .cfm files"""
    references = []
    search_pattern = re.escape(filename)  # Escape special regex characters
    
    # Search in all .cfm files
    for cfm_file in Path(root_folder).rglob("*.cfm"):
        # Skip the file itself if it's in the qry folder
        if "/qry/" in str(cfm_file) and cfm_file.name == filename:
            continue
            
        try:
            with open(cfm_file, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
                
                # Look for cfinclude references
                if re.search(rf'cfinclude.*{search_pattern}', content, re.IGNORECASE):
                    references.append(str(cfm_file))
                    
        except Exception as e:
            print(f"⚠️  Warning: Could not read {cfm_file}: {e}")
    
    return references

def analyze_qry_files(project_root):
    """Main function to analyze all qry files"""
    qry_folder = os.path.join(project_root, "include", "qry")
    
    print("🔍 TAO QRY Files Usage Analysis")
    print("=" * 50)
    print(f"📂 Scanning: {qry_folder}")
    print(f"🔎 Searching in: {project_root}")
    print()
    
    # Get all qry files
    qry_files = get_qry_files(qry_folder)
    
    if not qry_files:
        print("❌ No .cfm files found in qry folder!")
        return
    
    print(f"📋 Found {len(qry_files)} files in qry folder")
    print()
    
    # Track results
    used_files = []
    unused_files = []
    file_references = {}
    
    # Check each file
    for i, filename in enumerate(qry_files, 1):
        print(f"📄 [{i:3d}/{len(qry_files)}] Checking: {filename}", end=" ... ")
        
        references = search_for_references(project_root, filename)
        
        if references:
            print(f"✅ Used ({len(references)} references)")
            used_files.append(filename)
            file_references[filename] = references
        else:
            print("❌ Not referenced")
            unused_files.append(filename)
    
    # Print summary
    print()
    print("📊 SUMMARY")
    print("=" * 50)
    print(f"✅ Used files: {len(used_files)}")
    print(f"❌ Unused files: {len(unused_files)}")
    print(f"📈 Usage rate: {len(used_files)}/{len(qry_files)} ({len(used_files)/len(qry_files)*100:.1f}%)")
    print()
    
    # Show unused files
    if unused_files:
        print("🗑️  UNUSED FILES (Safe to delete)")
        print("-" * 40)
        for filename in unused_files:
            file_path = os.path.join(qry_folder, filename)
            file_size = os.path.getsize(file_path) if os.path.exists(file_path) else 0
            print(f"   • {filename} ({file_size} bytes)")
        print()
    
    # Show most referenced files
    if used_files:
        print("🔥 TOP REFERENCED FILES")
        print("-" * 40)
        # Sort by number of references
        sorted_files = sorted(file_references.items(), key=lambda x: len(x[1]), reverse=True)
        for filename, refs in sorted_files[:10]:  # Top 10
            print(f"   • {filename} ({len(refs)} references)")
        print()
    
    # Generate deletion script
    if unused_files:
        script_path = os.path.join(project_root, "delete_unused_qry_files.bat")
        with open(script_path, 'w') as f:
            f.write("@echo off\n")
            f.write("REM Batch script to delete unused QRY files\n")
            f.write("REM Generated by find_unused_qry_files.py\n")
            f.write("REM Review before running!\n\n")
            f.write("echo Deleting unused QRY files...\n")
            for filename in unused_files:
                file_path = os.path.join(qry_folder, filename).replace('/', '\\')
                f.write(f'del "{file_path}"\n')
            f.write("echo Done!\n")
            f.write("pause\n")
        
        print(f"💾 Generated deletion script: {script_path}")
        print("⚠️  REVIEW THE SCRIPT BEFORE RUNNING IT!")
    
    return {
        'used_files': used_files,
        'unused_files': unused_files,
        'file_references': file_references
    }

if __name__ == "__main__":
    # Set the project root directory
    project_root = r"c:\Users\xkking\new tao dev\dev-subdomain"
    
    try:
        results = analyze_qry_files(project_root)
        print("\n✨ Analysis complete!")
        
    except KeyboardInterrupt:
        print("\n🛑 Analysis cancelled by user")
    except Exception as e:
        print(f"\n💥 Error during analysis: {e}")
