// FILE: /repositories/ActionUserRepository.cfc
// GENERATED BY: TAO Audit — 2026-03-16
// MIGRATE: maps to Go internal/repository/action_user_repository.go

component
    displayName="ActionUserRepository"
    hint="All SQL for actionusers table. No business logic. Called only by ActionUserService."
    output="false"
{

    /**
     * List action user overrides
     * Replaces: /qry/getActionUsers.cfm
     */
    public query function listByUser(required numeric userId) {
        return queryExecute("
            SELECT au.auid, au.actionID, au.userID,
                   au.actionDaysNo, au.actionDaysRecurring, au.isUnique,
                   a.actionTitle, a.actionNo, a.systemID,
                   s.systemName
            FROM actionusers au
            INNER JOIN fuactions a ON a.actionID = au.actionID
            INNER JOIN fusystems s ON s.systemID = a.systemID
            WHERE au.userID = :userId
            ORDER BY s.systemName, a.actionNo
        ", { userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * Update action user overrides
     * Replaces: /qry/updateActionUsers.cfm + 4 variants
     */
    public void function update(
        required numeric auId,
        numeric actionDaysNo = -1,
        numeric actionDaysRecurring = -1
    ) {
        var setClauses = [];
        var params = { auId: { value: arguments.auId, cfsqltype: "CF_SQL_INTEGER" } };

        if (arguments.actionDaysNo >= 0) {
            arrayAppend(setClauses, "actionDaysNo = :daysNo");
            params.daysNo = { value: arguments.actionDaysNo, cfsqltype: "CF_SQL_INTEGER" };
        }
        if (arguments.actionDaysRecurring >= 0) {
            arrayAppend(setClauses, "actionDaysRecurring = :daysRecurring");
            params.daysRecurring = { value: arguments.actionDaysRecurring, cfsqltype: "CF_SQL_INTEGER" };
        }

        if (arrayLen(setClauses) == 0) return;

        queryExecute("
            UPDATE actionusers SET #arrayToList(setClauses, ', ')#
            WHERE auid = :auId
        ", params);
    }

    /**
     * Restore action users to defaults
     * Replaces: /qry/restoreActionUsers.cfm
     */
    public void function restoreDefaults(required numeric userId, required numeric systemId) {
        queryExecute("
            UPDATE actionusers au
            INNER JOIN fuactions a ON a.actionID = au.actionID
            SET au.actionDaysNo = a.actionDaysNo,
                au.actionDaysRecurring = a.actionDaysRecurring
            WHERE au.userID = :userId
              AND a.systemID = :systemId
        ", {
            userId:   { value: arguments.userId,   cfsqltype: "CF_SQL_INTEGER" },
            systemId: { value: arguments.systemId, cfsqltype: "CF_SQL_INTEGER" }
        });
    }

}
