// FILE: /repositories/ContactRepository.cfc
// GENERATED BY: TAO Audit — 2026-03-16
// MIGRATE: maps to Go internal/repository/contact_repository.go

component
    displayName="ContactRepository"
    hint="All SQL for contactdetails table. No business logic. Called only by ContactService."
    output="false"
{

    /**
     * Find a single contact by ID
     * Replaces: /qry/details_451_1.cfm, /qry/contact_info.cfm
     */
    public query function findById(required numeric contactId) {
        return queryExecute("
            SELECT
                d.contactid, d.userid, d.contactFullName, d.contacttitle,
                d.recordname, d.contactNickname, d.contactBirthday,
                d.contactMeetingDate, d.contactMeetingLoc, d.refer_contact_id,
                d.contactStatus, d.contactCreationDate, d.contactLastUpdated,
                d.contactphoto, d.contactPronoun,
                d.newsletter_yn, d.googlealert_yn, d.socialmedia_yn
            FROM contactdetails d
            INNER JOIN taousers u ON u.userid = d.userid
            WHERE d.contactID = :contactId
              AND d.isdeleted = 0
        ", { contactId: { value: arguments.contactId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * List contacts for a user with optional filtering
     * Replaces: /qry/contacts.cfm, /qry/contacts_all.cfm, /qry/contacts_all_tabs.cfm
     */
    public query function listByUser(required numeric userId, string status = "", numeric limit = 0) {
        var sql = "
            SELECT
                d.contactid, d.contactFullName, d.contacttitle, d.recordname,
                d.contactNickname, d.contactStatus, d.contactphoto,
                d.contactCreationDate, d.contactLastUpdated
            FROM contactdetails d
            WHERE d.userid = :userId
              AND d.isdeleted = 0
        ";
        var params = { userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" } };

        if (len(trim(arguments.status))) {
            sql &= " AND d.contactStatus = :status";
            params.status = { value: arguments.status, cfsqltype: "CF_SQL_VARCHAR" };
        }

        sql &= " ORDER BY d.contactFullName ASC";

        if (arguments.limit > 0) {
            sql &= " LIMIT :lim";
            params.lim = { value: arguments.limit, cfsqltype: "CF_SQL_INTEGER" };
        }

        return queryExecute(sql, params);
    }

    /**
     * Search contacts by name
     * Replaces: /qry/lookup_contacts.cfm
     */
    public query function search(required numeric userId, required string term) {
        return queryExecute("
            SELECT contactid, contactFullName, recordname, contactphoto
            FROM contactdetails
            WHERE userid = :userId
              AND isdeleted = 0
              AND (contactFullName LIKE :term OR recordname LIKE :term)
            ORDER BY contactFullName ASC
            LIMIT 50
        ", {
            userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" },
            term: { value: "%" & arguments.term & "%", cfsqltype: "CF_SQL_VARCHAR" }
        });
    }

    /**
     * Insert a new contact
     * Replaces: /qry/INScontactdetails.cfm, /qry/InsertContact_188_*.cfm
     */
    public numeric function insert(required struct data) {
        var result = queryExecute("
            INSERT INTO contactdetails (
                userid, contactFullName, contacttitle, recordname,
                contactNickname, contactBirthday, contactPronoun,
                contactStatus, contactCreationDate
            ) VALUES (
                :userId, :fullName, :title, :recordName,
                :nickname, :birthday, :pronoun,
                :status, NOW()
            )
        ", {
            userId:     { value: arguments.data.userid,          cfsqltype: "CF_SQL_INTEGER" },
            fullName:   { value: arguments.data.contactFullName, cfsqltype: "CF_SQL_VARCHAR" },
            title:      { value: arguments.data.contacttitle ?: "", cfsqltype: "CF_SQL_VARCHAR", null: !len(trim(arguments.data.contacttitle ?: "")) },
            recordName: { value: arguments.data.recordname ?: "", cfsqltype: "CF_SQL_VARCHAR", null: !len(trim(arguments.data.recordname ?: "")) },
            nickname:   { value: arguments.data.contactNickname ?: "", cfsqltype: "CF_SQL_VARCHAR", null: !len(trim(arguments.data.contactNickname ?: "")) },
            birthday:   { value: arguments.data.contactBirthday ?: "", cfsqltype: "CF_SQL_DATE", null: !len(trim(arguments.data.contactBirthday ?: "")) },
            pronoun:    { value: arguments.data.contactPronoun ?: "", cfsqltype: "CF_SQL_VARCHAR", null: !len(trim(arguments.data.contactPronoun ?: "")) },
            status:     { value: arguments.data.contactStatus ?: "Active", cfsqltype: "CF_SQL_VARCHAR" }
        }, { result: "insertResult" });

        return insertResult.generatedKey;
    }

    /**
     * Update a contact record
     * Replaces: /qry/remoteUpdateC.cfm, /qry/updateContactUnique.cfm
     */
    public void function save(required numeric contactId, required struct data) {
        var setClauses = [];
        var params = { contactId: { value: arguments.contactId, cfsqltype: "CF_SQL_INTEGER" } };

        var allowedFields = {
            "contactFullName": "CF_SQL_VARCHAR",
            "contacttitle": "CF_SQL_VARCHAR",
            "recordname": "CF_SQL_VARCHAR",
            "contactNickname": "CF_SQL_VARCHAR",
            "contactBirthday": "CF_SQL_DATE",
            "contactPronoun": "CF_SQL_VARCHAR",
            "contactStatus": "CF_SQL_VARCHAR",
            "contactphoto": "CF_SQL_VARCHAR",
            "refer_contact_id": "CF_SQL_INTEGER",
            "newsletter_yn": "CF_SQL_CHAR",
            "googlealert_yn": "CF_SQL_CHAR",
            "socialmedia_yn": "CF_SQL_CHAR"
        };

        for (var field in arguments.data) {
            if (structKeyExists(allowedFields, field)) {
                arrayAppend(setClauses, "#field# = :#field#");
                params[field] = { value: arguments.data[field], cfsqltype: allowedFields[field], null: !len(trim(arguments.data[field])) };
            }
        }

        if (arrayLen(setClauses) == 0) return;

        arrayAppend(setClauses, "contactLastUpdated = NOW()");

        queryExecute("
            UPDATE contactdetails
            SET #arrayToList(setClauses, ', ')#
            WHERE contactID = :contactId
        ", params);
    }

    /**
     * Soft-delete a contact
     * Replaces: scattered delete patterns
     */
    public void function softDelete(required numeric contactId) {
        queryExecute("
            UPDATE contactdetails
            SET isdeleted = 1, contactLastUpdated = NOW()
            WHERE contactID = :contactId
        ", { contactId: { value: arguments.contactId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * Check duplicate by email
     * Replaces: /qry/duplicatesByEmail.cfm
     */
    public query function findDuplicatesByEmail(required numeric userId, required string email) {
        return queryExecute("
            SELECT d.contactid, d.contactFullName, ci.valueText AS email
            FROM contactdetails d
            INNER JOIN contactitems ci ON ci.contactid = d.contactid
            WHERE d.userid = :userId
              AND d.isdeleted = 0
              AND ci.valueText = :email
              AND ci.itemtype IN ('Email','Business Email','Personal Email')
        ", {
            userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" },
            email:  { value: arguments.email,  cfsqltype: "CF_SQL_VARCHAR" }
        });
    }

    /**
     * Check duplicate by name
     * Replaces: /qry/duplicatesByName.cfm
     */
    public query function findDuplicatesByName(required numeric userId, required string fullName) {
        return queryExecute("
            SELECT contactid, contactFullName
            FROM contactdetails
            WHERE userid = :userId
              AND isdeleted = 0
              AND contactFullName = :fullName
        ", {
            userId:   { value: arguments.userId,   cfsqltype: "CF_SQL_INTEGER" },
            fullName: { value: arguments.fullName,  cfsqltype: "CF_SQL_VARCHAR" }
        });
    }

    /**
     * List birthdays for a user
     * Replaces: /qry/birthdays.cfm
     */
    public query function listBirthdays(required numeric userId) {
        return queryExecute("
            SELECT contactid, contactFullName, contactBirthday
            FROM contactdetails
            WHERE userid = :userId
              AND isdeleted = 0
              AND contactBirthday IS NOT NULL
            ORDER BY MONTH(contactBirthday), DAY(contactBirthday)
        ", { userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * Check email exists for user
     * Replaces: /qry/emailcheck.cfm
     */
    public boolean function emailExists(required numeric userId, required string email) {
        var result = queryExecute("
            SELECT COUNT(*) AS cnt
            FROM contactdetails d
            INNER JOIN contactitems ci ON ci.contactid = d.contactid
            WHERE d.userid = :userId
              AND d.isdeleted = 0
              AND ci.valueText = :email
        ", {
            userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" },
            email:  { value: arguments.email,  cfsqltype: "CF_SQL_VARCHAR" }
        });
        return result.cnt > 0;
    }

}
