// FILE: /repositories/EventRepository.cfc
// GENERATED BY: TAO Audit — 2026-03-16
// MIGRATE: maps to Go internal/repository/event_repository.go

component
    displayName="EventRepository"
    hint="All SQL for events table. No business logic. Called only by EventService."
    output="false"
{

    /**
     * Find an event by ID
     * Replaces: /qry/appoint-info.cfm, /qry/eventdetails_*.cfm
     */
    public query function findById(required numeric eventId) {
        return queryExecute("
            SELECT
                e.eventid, e.userid, e.eventtitle, e.eventnotes,
                e.eventstart, e.eventend, e.eventlocation,
                e.eventstatus, e.eventtype, e.contactid,
                e.isdeleted, e.created_at, e.updated_at,
                et.eventtypename
            FROM events e
            LEFT JOIN eventtypes et ON et.eventtypeid = e.eventtype
            WHERE e.eventid = :eventId
              AND e.isdeleted = 0
        ", { eventId: { value: arguments.eventId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * List events for a user
     * Replaces: /qry/events.cfm, /qry/events_byuser.cfm, /qry/eventresults.cfm
     */
    public query function listByUser(required numeric userId, string dateFrom = "", string dateTo = "") {
        var sql = "
            SELECT
                e.eventid, e.eventtitle, e.eventstart, e.eventend,
                e.eventlocation, e.eventstatus, e.eventtype,
                e.contactid, cd.contactFullName,
                et.eventtypename
            FROM events e
            LEFT JOIN contactdetails cd ON cd.contactid = e.contactid
            LEFT JOIN eventtypes et ON et.eventtypeid = e.eventtype
            WHERE e.userid = :userId
              AND e.isdeleted = 0
        ";
        var params = { userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" } };

        if (len(trim(arguments.dateFrom))) {
            sql &= " AND e.eventstart >= :dateFrom";
            params.dateFrom = { value: arguments.dateFrom, cfsqltype: "CF_SQL_DATE" };
        }
        if (len(trim(arguments.dateTo))) {
            sql &= " AND e.eventstart <= :dateTo";
            params.dateTo = { value: arguments.dateTo, cfsqltype: "CF_SQL_DATE" };
        }

        sql &= " ORDER BY e.eventstart DESC";

        return queryExecute(sql, params);
    }

    /**
     * Insert a new event
     * Replaces: /qry/appoint-add.cfm
     */
    public numeric function insert(required struct data) {
        queryExecute("
            INSERT INTO events (
                userid, eventtitle, eventnotes, eventstart, eventend,
                eventlocation, eventstatus, eventtype, contactid, created_at
            ) VALUES (
                :userId, :title, :notes, :start, :end,
                :location, :status, :type, :contactId, NOW()
            )
        ", {
            userId:    { value: arguments.data.userid,        cfsqltype: "CF_SQL_INTEGER" },
            title:     { value: arguments.data.eventtitle,    cfsqltype: "CF_SQL_VARCHAR" },
            notes:     { value: arguments.data.eventnotes ?: "", cfsqltype: "CF_SQL_VARCHAR", null: !len(trim(arguments.data.eventnotes ?: "")) },
            start:     { value: arguments.data.eventstart,    cfsqltype: "CF_SQL_TIMESTAMP" },
            end:       { value: arguments.data.eventend ?: "", cfsqltype: "CF_SQL_TIMESTAMP", null: !len(trim(arguments.data.eventend ?: "")) },
            location:  { value: arguments.data.eventlocation ?: "", cfsqltype: "CF_SQL_VARCHAR", null: !len(trim(arguments.data.eventlocation ?: "")) },
            status:    { value: arguments.data.eventstatus ?: "Active", cfsqltype: "CF_SQL_VARCHAR" },
            type:      { value: arguments.data.eventtype ?: 0, cfsqltype: "CF_SQL_INTEGER", null: !val(arguments.data.eventtype ?: 0) },
            contactId: { value: arguments.data.contactid ?: 0, cfsqltype: "CF_SQL_INTEGER", null: !val(arguments.data.contactid ?: 0) }
        }, { result: "insertResult" });

        return insertResult.generatedKey;
    }

    /**
     * Update an event
     * Replaces: /qry/appoint-update.cfm, /qry/updateEventData.cfm, /qry/update_cal.cfm
     */
    public void function save(required numeric eventId, required struct data) {
        var setClauses = [];
        var params = { eventId: { value: arguments.eventId, cfsqltype: "CF_SQL_INTEGER" } };

        var allowedFields = {
            "eventtitle": "CF_SQL_VARCHAR",
            "eventnotes": "CF_SQL_VARCHAR",
            "eventstart": "CF_SQL_TIMESTAMP",
            "eventend": "CF_SQL_TIMESTAMP",
            "eventlocation": "CF_SQL_VARCHAR",
            "eventstatus": "CF_SQL_VARCHAR",
            "eventtype": "CF_SQL_INTEGER",
            "contactid": "CF_SQL_INTEGER"
        };

        for (var field in arguments.data) {
            if (structKeyExists(allowedFields, field)) {
                arrayAppend(setClauses, "#field# = :#field#");
                params[field] = { value: arguments.data[field], cfsqltype: allowedFields[field], null: !len(trim(arguments.data[field])) };
            }
        }

        if (arrayLen(setClauses) == 0) return;
        arrayAppend(setClauses, "updated_at = NOW()");

        queryExecute("
            UPDATE events
            SET #arrayToList(setClauses, ', ')#
            WHERE eventid = :eventId
        ", params);
    }

    /**
     * Soft-delete an event
     */
    public void function softDelete(required numeric eventId) {
        queryExecute("
            UPDATE events SET isdeleted = 1, updated_at = NOW()
            WHERE eventid = :eventId
        ", { eventId: { value: arguments.eventId, cfsqltype: "CF_SQL_INTEGER" } });
    }

}
