// FILE: /repositories/NoteRepository.cfc
// GENERATED BY: TAO Audit — 2026-03-16
// MIGRATE: maps to Go internal/repository/note_repository.go

component
    displayName="NoteRepository"
    hint="All SQL for notes table. No business logic. Called only by NoteService."
    output="false"
{

    /**
     * Find note by ID
     * Replaces: /qry/getNoteDetails.cfm
     */
    public query function findById(required numeric noteId) {
        return queryExecute("
            SELECT n.noteid, n.userid, n.contactid, n.notetitle,
                   n.notebody, n.notedate, n.notetype, n.isdeleted,
                   cd.contactFullName
            FROM notes n
            LEFT JOIN contactdetails cd ON cd.contactid = n.contactid
            WHERE n.noteid = :noteId
        ", { noteId: { value: arguments.noteId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * List notes by contact
     * Replaces: /qry/notesContact.cfm
     */
    public query function listByContact(required numeric contactId, required numeric userId) {
        return queryExecute("
            SELECT n.noteid, n.notetitle, n.notebody, n.notedate, n.notetype
            FROM notes n
            WHERE n.contactid = :contactId
              AND n.userid = :userId
              AND n.isdeleted = 0
            ORDER BY n.notedate DESC
        ", {
            contactId: { value: arguments.contactId, cfsqltype: "CF_SQL_INTEGER" },
            userId:    { value: arguments.userId,    cfsqltype: "CF_SQL_INTEGER" }
        });
    }

    /**
     * List notes by event
     * Replaces: /qry/notesEvent.cfm
     */
    public query function listByEvent(required numeric eventId, required numeric userId) {
        return queryExecute("
            SELECT n.noteid, n.notetitle, n.notebody, n.notedate, n.notetype
            FROM notes n
            WHERE n.eventid = :eventId
              AND n.userid = :userId
              AND n.isdeleted = 0
            ORDER BY n.notedate DESC
        ", {
            eventId: { value: arguments.eventId, cfsqltype: "CF_SQL_INTEGER" },
            userId:  { value: arguments.userId,  cfsqltype: "CF_SQL_INTEGER" }
        });
    }

    /**
     * List notes by relationship/system
     * Replaces: /qry/notesrelationship.cfm
     */
    public query function listByRelationship(required numeric suId, required numeric userId) {
        return queryExecute("
            SELECT n.noteid, n.notetitle, n.notebody, n.notedate, n.notetype
            FROM notes n
            WHERE n.suid = :suId
              AND n.userid = :userId
              AND n.isdeleted = 0
            ORDER BY n.notedate DESC
        ", {
            suId:   { value: arguments.suId,   cfsqltype: "CF_SQL_INTEGER" },
            userId: { value: arguments.userId,  cfsqltype: "CF_SQL_INTEGER" }
        });
    }

    /**
     * Insert a note
     * Replaces: /qry/note-add.cfm, InsertNote_*.cfm (8 copies)
     */
    public numeric function insert(required struct data) {
        queryExecute("
            INSERT INTO notes (userid, contactid, eventid, suid, notetitle, notebody, notedate, notetype)
            VALUES (:userId, :contactId, :eventId, :suId, :title, :body, NOW(), :type)
        ", {
            userId:    { value: arguments.data.userid,    cfsqltype: "CF_SQL_INTEGER" },
            contactId: { value: arguments.data.contactid ?: 0, cfsqltype: "CF_SQL_INTEGER", null: !val(arguments.data.contactid ?: 0) },
            eventId:   { value: arguments.data.eventid ?: 0,   cfsqltype: "CF_SQL_INTEGER", null: !val(arguments.data.eventid ?: 0) },
            suId:      { value: arguments.data.suid ?: 0,      cfsqltype: "CF_SQL_INTEGER", null: !val(arguments.data.suid ?: 0) },
            title:     { value: arguments.data.notetitle ?: "", cfsqltype: "CF_SQL_VARCHAR" },
            body:      { value: arguments.data.notebody ?: "",  cfsqltype: "CF_SQL_LONGVARCHAR" },
            type:      { value: arguments.data.notetype ?: "",  cfsqltype: "CF_SQL_VARCHAR" }
        }, { result: "insertResult" });

        return insertResult.generatedKey;
    }

    /**
     * Soft-delete a note
     * Replaces: /qry/DeleteNote_*.cfm (3 variants)
     */
    public void function softDelete(required numeric noteId) {
        queryExecute("
            UPDATE notes SET isdeleted = 1
            WHERE noteid = :noteId
        ", { noteId: { value: arguments.noteId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * Get links for a note
     * Replaces: /qry/getLinksByNoteId.cfm
     */
    public query function getLinks(required numeric noteId) {
        return queryExecute("
            SELECT linkid, linkurl, linktitle, linktype
            FROM notelinks
            WHERE noteid = :noteId
        ", { noteId: { value: arguments.noteId, cfsqltype: "CF_SQL_INTEGER" } });
    }

}
