// FILE: /repositories/NotificationRepository.cfc
// GENERATED BY: TAO Audit — 2026-03-16
// MIGRATE: maps to Go internal/repository/notification_repository.go

component
    displayName="NotificationRepository"
    hint="All SQL for funotifications table. No business logic. Called only by NotificationService."
    output="false"
{

    /**
     * Find a notification by ID
     * Replaces: /qry/getNotificationByID.cfm
     */
    public query function findById(required numeric notId) {
        return queryExecute("
            SELECT
                n.notID, n.actionID, n.userID, n.suID,
                n.notTimeStamp, n.notStartDate, n.notEndDate,
                n.notStatus, n.notNotes, n.ispastdue,
                f.systemID, f.contactID, f.suStatus,
                a.actionNo, a.actionDetails, a.actionTitle, a.navToURL,
                au.actionDaysNo, au.actionDaysRecurring,
                a.actionNotes, a.actionInfo,
                ns.checktype, ns.delstart, ns.delend, ns.status_color
            FROM funotifications n
            INNER JOIN fusystemusers f ON f.suID = n.suID
            INNER JOIN fuactions a ON a.actionID = n.actionID
            INNER JOIN actionusers au ON a.actionID = au.actionID AND au.userID = f.userID
            INNER JOIN notstatuses ns ON ns.notstatus = n.notStatus
            WHERE n.notID = :notId
              AND n.isdeleted = 0
        ", { notId: { value: arguments.notId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * List active notifications for a user
     * Replaces: /qry/notsActive_510_1.cfm, /qry/notsactive.cfm
     */
    public query function listActive(required numeric userId, string hideCompleted = "N") {
        var sql = "
            SELECT
                n.notID, n.actionID, n.userID, n.suID,
                n.notStartDate, n.notEndDate, n.notStatus, n.notNotes, n.ispastdue,
                f.systemID, f.contactID, f.suStatus,
                a.actionNo, a.actionDetails, a.actionTitle, a.navToURL,
                au.actionDaysNo, au.actionDaysRecurring,
                ns.checktype, ns.status_color,
                cd.contactFullName, cd.recordname
            FROM funotifications n
            INNER JOIN fusystemusers f ON f.suID = n.suID
            INNER JOIN fuactions a ON a.actionID = n.actionID
            INNER JOIN actionusers au ON a.actionID = au.actionID AND au.userID = f.userID
            INNER JOIN notstatuses ns ON ns.notstatus = n.notStatus
            INNER JOIN contactdetails cd ON cd.contactid = f.contactID
            WHERE n.userID = :userId
              AND n.isdeleted = 0
              AND n.notStartDate <= NOW()
              AND n.notStatus IN ('Pending','Past Due')
        ";
        var params = { userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" } };

        if (arguments.hideCompleted == "Y") {
            sql &= " AND n.notStatus != 'Completed'";
        }

        sql &= " ORDER BY n.notStartDate ASC, a.actionNo ASC";

        return queryExecute(sql, params);
    }

    /**
     * List all notifications for a user
     * Replaces: /qry/notsall.cfm
     */
    public query function listAll(required numeric userId, numeric limit = 500) {
        return queryExecute("
            SELECT
                n.notID, n.actionID, n.suID,
                n.notStartDate, n.notEndDate, n.notStatus, n.notNotes,
                f.contactID, cd.contactFullName,
                a.actionTitle, a.actionDetails
            FROM funotifications n
            INNER JOIN fusystemusers f ON f.suID = n.suID
            INNER JOIN fuactions a ON a.actionID = n.actionID
            INNER JOIN contactdetails cd ON cd.contactid = f.contactID
            WHERE n.userID = :userId
              AND n.isdeleted = 0
            ORDER BY n.notStartDate DESC
            LIMIT :lim
        ", {
            userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" },
            lim:    { value: arguments.limit,  cfsqltype: "CF_SQL_INTEGER" }
        });
    }

    /**
     * List notifications by system enrollment
     * Replaces: /qry/getNotificationsBySystem.cfm, /qry/systemNotificationsActive.cfm
     */
    public query function listBySystem(required numeric suId) {
        return queryExecute("
            SELECT
                n.notID, n.actionID, n.suID,
                n.notStartDate, n.notEndDate, n.notStatus, n.notNotes, n.ispastdue,
                a.actionNo, a.actionTitle, a.actionDetails,
                ns.checktype, ns.status_color
            FROM funotifications n
            INNER JOIN fuactions a ON a.actionID = n.actionID
            INNER JOIN notstatuses ns ON ns.notstatus = n.notStatus
            WHERE n.suID = :suId
              AND n.isdeleted = 0
            ORDER BY a.actionNo ASC
        ", { suId: { value: arguments.suId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * Create a new notification
     * Replaces: /qry/addNotification.cfm + 9 page copies
     */
    public numeric function create(
        required numeric actionId,
        required numeric userId,
        required numeric suId,
        string notStartDate = "",
        string notStatus = "Pending"
    ) {
        queryExecute("
            INSERT INTO funotifications (actionID, userID, suID, notStartDate, notStatus, notTimeStamp, isdeleted)
            VALUES (:actionId, :userId, :suId, :startDate, :status, NOW(), 0)
        ", {
            actionId:  { value: arguments.actionId,     cfsqltype: "CF_SQL_INTEGER" },
            userId:    { value: arguments.userId,       cfsqltype: "CF_SQL_INTEGER" },
            suId:      { value: arguments.suId,         cfsqltype: "CF_SQL_INTEGER" },
            startDate: { value: arguments.notStartDate, cfsqltype: "CF_SQL_DATE", null: !len(trim(arguments.notStartDate)) },
            status:    { value: arguments.notStatus,    cfsqltype: "CF_SQL_VARCHAR" }
        }, { result: "insertResult" });

        return insertResult.generatedKey;
    }

    /**
     * Update notification status
     * Replaces: /qry/updateNotification.cfm, updateNotificationCompleted.cfm, updateNotificationNext.cfm
     */
    public void function updateStatus(
        required numeric notId,
        required string notStatus,
        string notEndDate = "",
        string notStartDate = ""
    ) {
        var sql = "UPDATE funotifications SET notStatus = :status";
        var params = {
            notId:  { value: arguments.notId,    cfsqltype: "CF_SQL_INTEGER" },
            status: { value: arguments.notStatus, cfsqltype: "CF_SQL_VARCHAR" }
        };

        if (len(trim(arguments.notStartDate))) {
            sql &= ", notStartDate = :startDate";
            params.startDate = { value: arguments.notStartDate, cfsqltype: "CF_SQL_DATE" };
        }
        if (arguments.notStatus == "Completed" || arguments.notStatus == "Skipped") {
            sql &= ", notEndDate = :endDate";
            params.endDate = { value: len(trim(arguments.notEndDate)) ? arguments.notEndDate : now(), cfsqltype: "CF_SQL_DATE" };
        }

        sql &= " WHERE notID = :notId";
        queryExecute(sql, params);
    }

    /**
     * Delete notifications by system enrollment
     * Replaces: /qry/delSystemNotifications.cfm, /qry/deleteNotificationBySystem.cfm
     */
    public void function deleteBySystem(required numeric suId) {
        queryExecute("
            UPDATE funotifications
            SET isdeleted = 1
            WHERE suID = :suId
        ", { suId: { value: arguments.suId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * List next upcoming notifications
     * Replaces: /qry/notsnext.cfm
     */
    public query function listNext(required numeric userId, numeric limit = 10) {
        return queryExecute("
            SELECT
                n.notID, n.suID, n.notStartDate, n.notStatus,
                a.actionTitle, cd.contactFullName
            FROM funotifications n
            INNER JOIN fusystemusers f ON f.suID = n.suID
            INNER JOIN fuactions a ON a.actionID = n.actionID
            INNER JOIN contactdetails cd ON cd.contactid = f.contactID
            WHERE n.userID = :userId
              AND n.isdeleted = 0
              AND n.notStatus = 'Pending'
              AND n.notStartDate > NOW()
            ORDER BY n.notStartDate ASC
            LIMIT :lim
        ", {
            userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" },
            lim:    { value: arguments.limit,  cfsqltype: "CF_SQL_INTEGER" }
        });
    }

}
