// FILE: /repositories/SystemRepository.cfc
// GENERATED BY: TAO Audit — 2026-03-16
// MIGRATE: maps to Go internal/repository/system_repository.go

component
    displayName="SystemRepository"
    hint="All SQL for fusystems table. No business logic. Called only by SystemService."
    output="false"
{

    /**
     * Find a system by ID
     */
    public query function findById(required numeric systemId) {
        return queryExecute("
            SELECT systemID, systemName, systemScope, systemDescription,
                   systemStatus, isdeleted
            FROM fusystems
            WHERE systemID = :systemId
        ", { systemId: { value: arguments.systemId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * Find system by scope (Target, Maintenance, etc.)
     * Replaces: /qry/findSystemByScope.cfm, /qry/findscope.cfm
     */
    public query function findByScope(required string systemScope) {
        return queryExecute("
            SELECT systemID, systemName, systemScope, systemDescription
            FROM fusystems
            WHERE systemScope = :scope
              AND isdeleted = 0
        ", { scope: { value: arguments.systemScope, cfsqltype: "CF_SQL_VARCHAR" } });
    }

    /**
     * Find system by tag
     * Replaces: /qry/getSystemIdBasedOnTag.cfm
     */
    public query function findByTag(required string tagName) {
        return queryExecute("
            SELECT s.systemID, s.systemName
            FROM fusystems s
            WHERE s.systemTag = :tagName
              AND s.isdeleted = 0
        ", { tagName: { value: arguments.tagName, cfsqltype: "CF_SQL_VARCHAR" } });
    }

    /**
     * List active systems
     * Replaces: /qry/sysActive.cfm
     */
    public query function listActive() {
        return queryExecute("
            SELECT systemID, systemName, systemScope, systemDescription
            FROM fusystems
            WHERE isdeleted = 0
              AND systemStatus = 'Active'
            ORDER BY systemName
        ");
    }

}
