// FILE: /repositories/SystemUserRepository.cfc
// GENERATED BY: TAO Audit — 2026-03-16
// MIGRATE: maps to Go internal/repository/system_user_repository.go

component
    displayName="SystemUserRepository"
    hint="All SQL for fusystemusers table. No business logic. Called only by SystemUserService."
    output="false"
{

    /**
     * Find a system-user enrollment by ID
     * Replaces: /qry/getSystemUserByID.cfm
     */
    public query function findById(required numeric suId) {
        return queryExecute("
            SELECT su.suID, su.systemID, su.contactID, su.userID,
                   su.suTimeStamp, su.suStartDate, su.suEndDate,
                   su.suStatus, su.suNotes,
                   s.systemName, s.systemScope,
                   cd.contactFullName
            FROM fusystemusers su
            INNER JOIN fusystems s ON s.systemID = su.systemID
            INNER JOIN contactdetails cd ON cd.contactid = su.contactID
            WHERE su.suID = :suId
        ", { suId: { value: arguments.suId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * List enrollments by system
     * Replaces: /qry/getFuSystemUsersBySystemID.cfm
     */
    public query function listBySystemId(required numeric systemId, required numeric userId) {
        return queryExecute("
            SELECT su.suID, su.contactID, su.suStartDate, su.suStatus,
                   cd.contactFullName
            FROM fusystemusers su
            INNER JOIN contactdetails cd ON cd.contactid = su.contactID
            WHERE su.systemID = :systemId
              AND su.userID = :userId
            ORDER BY su.suStartDate DESC
        ", {
            systemId: { value: arguments.systemId, cfsqltype: "CF_SQL_INTEGER" },
            userId:   { value: arguments.userId,   cfsqltype: "CF_SQL_INTEGER" }
        });
    }

    /**
     * List active enrollments for a contact
     * Replaces: /qry/SystemsActiveContact.cfm
     */
    public query function listActiveByContact(required numeric contactId, required numeric userId) {
        return queryExecute("
            SELECT su.suID, su.systemID, su.suStartDate, su.suStatus,
                   s.systemName, s.systemScope
            FROM fusystemusers su
            INNER JOIN fusystems s ON s.systemID = su.systemID
            WHERE su.contactID = :contactId
              AND su.userID = :userId
              AND su.suStatus = 'Active'
            ORDER BY s.systemName
        ", {
            contactId: { value: arguments.contactId, cfsqltype: "CF_SQL_INTEGER" },
            userId:    { value: arguments.userId,    cfsqltype: "CF_SQL_INTEGER" }
        });
    }

    /**
     * Enroll a contact in a system
     * Replaces: /qry/addSystem.cfm, /qry/addfuSystemUsers.cfm
     */
    public numeric function create(
        required numeric systemId,
        required numeric contactId,
        required numeric userId,
        string suStartDate = "",
        string suStatus = "Active"
    ) {
        queryExecute("
            INSERT INTO fusystemusers (systemID, contactID, userID, suStartDate, suStatus, suTimeStamp)
            VALUES (:systemId, :contactId, :userId, :startDate, :status, NOW())
        ", {
            systemId:  { value: arguments.systemId,    cfsqltype: "CF_SQL_INTEGER" },
            contactId: { value: arguments.contactId,   cfsqltype: "CF_SQL_INTEGER" },
            userId:    { value: arguments.userId,      cfsqltype: "CF_SQL_INTEGER" },
            startDate: { value: len(trim(arguments.suStartDate)) ? arguments.suStartDate : now(), cfsqltype: "CF_SQL_DATE" },
            status:    { value: arguments.suStatus,    cfsqltype: "CF_SQL_VARCHAR" }
        }, { result: "insertResult" });

        return insertResult.generatedKey;
    }

    /**
     * Mark enrollment as completed
     * Replaces: /qry/updateSystemUserCompleted.cfm
     */
    public void function markCompleted(required numeric suId) {
        queryExecute("
            UPDATE fusystemusers
            SET suStatus = 'Completed', suEndDate = NOW()
            WHERE suID = :suId
        ", { suId: { value: arguments.suId, cfsqltype: "CF_SQL_INTEGER" } });
    }

}
