// FILE: /repositories/UserRepository.cfc
// GENERATED BY: TAO Audit — 2026-03-16
// MIGRATE: maps to Go internal/repository/user_repository.go

component
    displayName="UserRepository"
    hint="All SQL for taousers table. No business logic. Called only by UserService."
    output="false"
{

    /**
     * Find a user by ID
     * Replaces: /qry/findUserById.cfm, /qry/getUserDetails.cfm
     */
    public query function findById(required numeric userId) {
        return queryExecute("
            SELECT userid, username, useremail, userfirstname, userlastname,
                   userrole, userstatus, userphoto, usertimezone,
                   userdateformat, usercreationdate, userlastupdated
            FROM taousers
            WHERE userid = :userId
        ", { userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * List all active users
     * Replaces: /qry/fetchUsers.cfm, /qry/getUsers.cfm
     */
    public query function listAll(string status = "Active") {
        return queryExecute("
            SELECT userid, username, useremail, userfirstname, userlastname,
                   userrole, userstatus
            FROM taousers
            WHERE userstatus = :status
            ORDER BY userlastname, userfirstname
        ", { status: { value: arguments.status, cfsqltype: "CF_SQL_VARCHAR" } });
    }

    /**
     * Get account details
     * Replaces: /qry/myaccount.cfm
     */
    public query function getAccountDetails(required numeric userId) {
        return queryExecute("
            SELECT userid, username, useremail, userfirstname, userlastname,
                   userrole, userstatus, userphoto, usertimezone, userdateformat,
                   usercreationdate
            FROM taousers
            WHERE userid = :userId
        ", { userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" } });
    }

    /**
     * Update user profile
     */
    public void function save(required numeric userId, required struct data) {
        var setClauses = [];
        var params = { userId: { value: arguments.userId, cfsqltype: "CF_SQL_INTEGER" } };

        var allowedFields = {
            "userfirstname": "CF_SQL_VARCHAR",
            "userlastname": "CF_SQL_VARCHAR",
            "useremail": "CF_SQL_VARCHAR",
            "userphoto": "CF_SQL_VARCHAR",
            "usertimezone": "CF_SQL_VARCHAR",
            "userdateformat": "CF_SQL_VARCHAR"
        };

        for (var field in arguments.data) {
            if (structKeyExists(allowedFields, field)) {
                arrayAppend(setClauses, "#field# = :#field#");
                params[field] = { value: arguments.data[field], cfsqltype: allowedFields[field] };
            }
        }

        if (arrayLen(setClauses) == 0) return;
        arrayAppend(setClauses, "userlastupdated = NOW()");

        queryExecute("
            UPDATE taousers SET #arrayToList(setClauses, ', ')#
            WHERE userid = :userId
        ", params);
    }

}
